title: Michael West's Projects
description: This site is where I write-up all my projects to make them easily accesible to all of you!
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker